export const CLICK='CLICK';
export const UPDATE='UPDATE';
export const SEARCH='SEARCH';

export const FETCH_LOCATION_BEGIN='FETCH_LOCATION_BEGIN';
export const FETCH_LOCATION_SUCCESS='FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAILURE='FETCH_LOCATION_FAILURE';

// rst
export const FETCH_RST_BEGIN='FETCH_RST_BEGIN';
export const FETCH_RST_SUCCESS='FETCH_RST_SUCCESS';

// food
export const FETCH_FOOD_BEGIN='FETCH_FOOD_BEGIN';
export const FETCH_FOOD_SUCCESS='FETCH_FOOD_SUCCESS';

export const FETCH_CARD_SUCCES='FETCH_CARD_SUCCES';
export const FETCH_CARD_BEGIN='FETCH_CARD_BEGIN';